#include "math_ops.h"
#include <math.h>

// --------- FUNCTION IMPLEMENTATIONS ------------

float multiply(float x, float y) 
{
    return x * y;
}

float add(float x, float y) 
{
    return x + y;
}

float square(float x) 
{
    return x * x;
}

float cube(float x) 
{
    return x * x * x;
}

float mypow(float base, int exponent ) 
{
    float res = 1;
    for(int i = 0; i < exponent; i++) 
    {
        res *= base;
    }
    return res;
}

float sub(float a, float b)
{
    return a - b;
}

float divide(float a, float b)
{
    return a / b;
}

// Function generated by ChatGPT (with given permission to do so).
double factorial(int n) {
    double fact = 1;
    int i;

    for (i = 1; i <= n; i++) {
        fact *= i;
    }

    return fact;
}

// Function generated by ChatGPT (with given permission to do so).
double mysin(double x, int steps) {
    double result = 0.0;
    double rad = x * (acos(-1.0) / 180.0);  // Convert degrees to radians

    for (int i = 0; i < steps; i++) {
        double term = mypow(-1, i) * mypow(rad, 2 * i + 1) / factorial(2 * i + 1);
        result += term;
    }

    return result;
}

// Function generated by ChatGPT (with given permission to do so).
double mycos(double x, int steps){
    double result = 0.0;
    double rad = x * (acos(-1.0) / 180.0);
    
    for (int n = 0; n < steps; ++n) {
        double term = mypow(-1, n) * mypow(rad, 2 * n) / factorial(2 * n + 1);
        result += term;
    }
    
    return result;
}