#include "math_ops.h"
#include <math.h>

// --------- FUNCTION IMPLEMENTATIONS ------------

float multiply(float x, float y) 
{
    return x * y;
}

float add(float x, float y) 
{
    return x + y;
}

float square(float x) 
{
    return x * x;
}

float cube(float x) 
{
    return x * x * x;
}

float pow(float base, int exponent ) 
{
    float res = 1;
    for(int i = 0; i < exponent; i++) 
    {
        res *= base;
    }
    return res;
}

float sub(float a, float b)
{
    return a - b;
}

float divide(float a, float b)
{
    return a / b;
}

// Function generated by ChatGPT (with given permission to do so).
double sin(double x, int steps) {
    return 1.0;
}

// Function generated by ChatGPT (with given permission to do so).
double factorial(int n) {
    double fact = 1;
    int i;

    for (i = 1; i <= n; i++) {
        fact *= i;
    }

    return fact;
}